[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
ulid = { version = "1", features = ["uuid"] }
mongodb = "2.6"
chrono = { version = "0.4.26", features = ["serde"] }
bson = { version = "2.6.1", features = ["chrono"] }
serde = { version = "1.0.183", features = ["derive"] }
