version: "3"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lelo
      POSTGRES_PASSWORD: lelo
      POSTGRES_DB: lelo
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      
#  mongo:
#    image: mongo:4
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: lelo
#      MONGO_INITDB_ROOT_PASSWORD: lelo
#    volumes:
#      - "mongo-data:/data/db"
  
#  redis:
#    image: redis:7
#    ports:
#      - "6379:6379"

volumes:
  mongo-data:
  postgres-data: