version: "3"

services:
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: lelo
      MONGO_INITDB_ROOT_PASSWORD: lelo
  
#  redis:
#    image: redis:7
#    ports:
#      - "6379:6379"